// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartnerIntegrationBFF.API.Data;

#nullable disable

namespace PartnerIntegrationBFF.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261007131535_SeedPartners")]
    partial class SeedPartners
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.20");

            modelBuilder.Entity("PartnerIntegrationBFF.API.Entities.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartnerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartnerCode")
                        .IsUnique();

                    b.ToTable("Partners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "AcmeCorp",
                            PartnerCode = "P-1001"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Globex",
                            PartnerCode = "P-1002"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = false,
                            Name = "Umbrella",
                            PartnerCode = "P-1003"
                        });
                });

            modelBuilder.Entity("PartnerIntegrationBFF.API.Entities.PartnerTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId", "TransactionReference")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("PartnerIntegrationBFF.API.Entities.PartnerTransaction", b =>
                {
                    b.HasOne("PartnerIntegrationBFF.API.Entities.Partner", "Partner")
                        .WithMany("Transactions")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("PartnerIntegrationBFF.API.Entities.Partner", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
